### ISSUE TITLE
Can't build repo on Windows

### ISSUE THREAD

**Issue by dsherret** [denoland/docs#452]
I've been unable to get this repo building on Windows:

```
> $env:DENO_FUTURE=1 ; deno task build
Task build docusaurus build && cp -r src-deno/* build
[INFO] [en] Creating an optimized production build...
[ERROR] Loading of version failed for version current
[ERROR] Loading of version failed for version current
[ERROR] Loading of version failed for version current

Error: Unable to build website for locale en.
    at tryToBuildLocale (file:///V:/deno-docs/node_modules/@docusaurus/core/lib/commands/build.js:55:19)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async mapAsyncSequential (file:///V:/deno-docs/node_modules/@docusaurus/utils/lib/jsUtils.js:44:24)
    at async Command.build (file:///V:/deno-docs/node_modules/@docusaurus/core/lib/commands/build.js:82:21)
Caused by Error: EINVAL: invalid argument, stat
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:62:9)
    at __node_internal_uvException (ext:deno_node/internal/errors.ts:127:10)
    at denoErrorToNodeError (ext:deno_node/internal/errors.ts:1770:14)
    at ext:deno_node/_fs/_fs_stat.ts:138:95
    at eventLoopTick (ext:core/01_core.js:168:7)

[INFO] Docusaurus version: 3.1.1
Node version: v20.11.1
```

**Comment by thisisjofrank** [comment]
This now runs on windows, albeit slowly
